MONGODB:
  MONGODB_USERNAME: root
  MONGODB_PASSWORD: msdnmm
  MONGODB_DB_IM: im
  MONGODB_DB_EDU: edu_system
  MONGODB_URL: mongodb://192.168.0.158:27017

REDIS:
  REDIS_PASSWORD: msdnmm
  REDIS_URL: 192.168.0.158:6379
