MONGODB:
  MONGODB_USERNAME: root
  MONGODB_PASSWORD: msdnmm
  MONGODB_DB_IM: im
  MONGODB_DB_EDU: edu_system
  MONGODB_URL: mongodb://139.198.165.102:27017
  MONGODB_TEST_URL: mongodb://192.168.0.158:27017

REDIS:
  REDIS_PASSWORD: msdnmm
  REDIS_URL: 119.91.208.160:6379
  REDIS_TEST_URL: 192.168.0.158:6379
