version: '3'

services:
  server:
    image: quay.io/minio/minio:RELEASE.2023-02-10T18-48-39Z
    command: server --console-address ":9090" /data
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: msdnmm
      MINIO_BROWSER_REDIRECT_URL: http://192.168.0.158:5000
      MINIO_SERVER_URL: http://192.168.0.158:5001
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://192.168.0.158:5000/minio/health/live']
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - data:/data
    ports:
      - '5000:9000'
      - '5001:9090'

volumes:
  data:
